export const expedientes = [

  {
    id: '1',
    title: 'Expediente 1',
    description: 'Descripción del expediente 1',
    fechaLimite: '2025-10-03',
    relevancia: 5,
    especialidad: 'Psiquiatria',
    estado: 'Asignar',
    observaciones: ['Caso priorizado', 'Pendiente revisión'],
  },
  {
    id: '2',
    title: 'Expediente 2',
    description: 'Descripción del expediente 2',
    fechaLimite: '2025-10-05',
    relevancia: 4,
    especialidad: 'ORL',
    estado: 'Otros',
    observaciones: ['Falta documento adjunto'],
  },
  {
    id: '3',
    title: 'Expediente 3',
    description: 'Descripción del expediente 3',
    fechaLimite: '2025-10-10',
    relevancia: 2,
    especialidad: 'Med. Trabajo',
    estado: 'Asignar',
    observaciones: ['Se solicitó información adicional'],
  },
  {
    id: '4',
    title: 'Expediente 4',
    description: 'Descripción del expediente 4',
    fechaLimite: '2025-10-10',
    relevancia: 3,
    especialidad: 'Trauma',
    estado: 'Reclamar',
    observaciones: ['Pendiente revisión'],
  },
  {
    id: '5',
    title: 'Expediente 5',
    description: 'Descripción del expediente 5',
    fechaLimite: '2025-10-15',
    relevancia: 1,
    especialidad: 'Ginecologia',
    estado: 'Corregir',
    observaciones: ['Caso priorizado', 'Falta documento adjunto', 'En espera de respuesta'],
  },
  {
    id: '6',
    title: 'Expediente 6',
    description: 'Descripción del expediente 6',
    fechaLimite: '2025-10-08',
    relevancia: 5,
    especialidad: 'Maxilo Facial',
    estado: 'Documentacion',
    observaciones: ['Asignado a nuevo responsable'],
  },
  {
    id: '7',
    title: 'Expediente 7',
    description: 'Descripción del expediente 7',
    fechaLimite: '2025-10-01',
    relevancia: 2,
    especialidad: 'Neurología',
    estado: 'Asignar',
    observaciones: ['En espera de respuesta'],
  },
  {
    id: '8',
    title: 'Expediente 8',
    description: 'Descripción del expediente 8',
    fechaLimite: '2025-10-17',
    relevancia: 3,
    especialidad: 'Med. Legal',
    estado: 'Letrados',
    observaciones: ['Pendiente revisión', 'Falta documento adjunto'],
  },
  {
    id: '9',
    title: 'Expediente 9',
    description: 'Descripción del expediente 9',
    fechaLimite: '2025-10-02',
    relevancia: 1,
    especialidad: 'Neurología',
    estado: 'Q',
    observaciones: ['Caso priorizado'],
  },
  {
    id: '10',
    title: 'Expediente 10',
    description: 'Descripción del expediente 10',
    fechaLimite: '2025-10-03',
    relevancia: 4,
    especialidad: 'Neurocirugia',
    estado: 'Asignar',
    observaciones: ['Falta documento adjunto', 'Se solicitó información adicional'],
  },
  {
    id: '11',
    title: 'Expediente 11',
    description: 'Descripción del expediente 11',
    fechaLimite: '2025-10-04',
    relevancia: 5,
    especialidad: 'Psiquiatria',
    estado: 'Corregir',
    observaciones: ['En espera de respuesta'],
  },
  {
    id: '12',
    title: 'Expediente 12',
    description: 'Descripción del expediente 12',
    fechaLimite: '2025-10-06',
    relevancia: 3,
    especialidad: 'Med. Legal',
    estado: 'Documentacion',
    observaciones: ['Caso priorizado'],
  },
  {
    id: '13',
    title: 'Expediente 13',
    description: 'Descripción del expediente 13',
    fechaLimite: '2025-10-09',
    relevancia: 2,
    especialidad: 'Neurología',
    estado: 'Asignar',
    observaciones: ['Asignado a nuevo responsable'],
  },
  {
    id: '14',
    title: 'Expediente 14',
    description: 'Descripción del expediente 14',
    fechaLimite: '2025-10-09',
    relevancia: 1,
    especialidad: 'Med. Legal',
    estado: 'Reclamar',
    observaciones: ['Requiere actualización de datos'],
  },
  {
    id: '15',
    title: 'Expediente 15',
    description: 'Descripción del expediente 15',
    fechaLimite: '2025-10-10',
    relevancia: 4,
    especialidad: 'Psiquiatria',
    estado: 'Asignar',
    observaciones: ['Falta documento adjunto','Pendiente revisión'],
  },
  {
    id: '16',
    title: 'Expediente 16',
    description: 'Descripción del expediente 16',
    fechaLimite: '2025-10-08',
    relevancia: 2,
    especialidad: 'Oftalmologia',
    estado: 'Otros',
    observaciones: ['Se solicitó información adicional'],
  },
  {
    id: '17',
    title: 'Expediente 17',
    description: 'Descripción del expediente 17',
    fechaLimite: '2025-10-11',
    relevancia: 3,
    especialidad: 'Trauma',
    estado: 'Asignar',
    observaciones: ['Pendiente revisión'],
  },
  {
    id: '18',
    title: 'Expediente 18',
    description: 'Descripción del expediente 18',
    fechaLimite: '2025-10-12',
    relevancia: 5,
    especialidad: 'Neurofisiologia',
    estado: 'Asignar',
    observaciones: ['Caso priorizado','Falta documento adjunto'],
  },
  {
    id: '19',
    title: 'Expediente 19',
    description: 'Descripción del expediente 19',
    fechaLimite: '2025-10-13',
    relevancia: 4,
    especialidad: 'Ginecologia',
    estado: 'Documentacion',
    observaciones: ['Se solicitó información adicional'],
  },
  {
    id: '20',
    title: 'Expediente 20',
    description: 'Descripción del expediente 20',
    fechaLimite: '2025-10-13',
    relevancia: 1,
    especialidad: 'Med. Trabajo',
    estado: 'Asignar',
    observaciones: ['Asignado a nuevo responsable'],
  },
  {
    id: '21',
    title: 'Expediente 21',
    description: 'Descripción del expediente 21',
    fechaLimite: '2025-10-15',
    relevancia: 2,
    especialidad: 'Maxilo Facial',
    estado: 'Q',
    observaciones: ['En espera de respuesta'],
  },
  {
    id: '22',
    title: 'Expediente 22',
    description: 'Descripción del expediente 22',
    fechaLimite: '2025-10-16',
    relevancia: 3,
    especialidad: 'Oftalmologia',
    estado: 'Reclamar',
    observaciones: ['Caso priorizado','Pendiente revisión'],
  },
  {
    id: '23',
    title: 'Expediente 23',
    description: 'Descripción del expediente 23',
    fechaLimite: '2025-10-18',
    relevancia: 1,
    especialidad: 'Neurología',
    estado: 'Letrados',
    observaciones: ['Falta documento adjunto'],
  },
  {
    id: '24',
    title: 'Expediente 24',
    description: 'Descripción del expediente 24',
    fechaLimite: '2025-10-19',
    relevancia: 4,
    especialidad: 'Trauma',
    estado: 'Otros',
    observaciones: ['Requiere actualización de datos'],
  },
  {
    id: '25',
    title: 'Expediente 25',
    description: 'Descripción del expediente 25',
    fechaLimite: '2025-10-20',
    relevancia: 5,
    especialidad: 'Med. Trabajo',
    estado: 'Asignar',
    observaciones: ['Pendiente revisión', 'Caso priorizado'],
  },
  {
    id: '26',
    title: 'Expediente 26',
    description: 'Descripción del expediente 26',
    fechaLimite: '2025-10-21',
    relevancia: 2,
    especialidad: 'Psiquiatria',
    estado: 'Q',
    observaciones: ['Falta documento adjunto'],
  },
  {
    id: '27',
    title: 'Expediente 27',
    description: 'Descripción del expediente 27',
    fechaLimite: '2025-10-22',
    relevancia: 3,
    especialidad: 'Maxilo Facial',
    estado: 'Asignar',
    observaciones: ['Se solicitó información adicional'],
  },
  {
    id: '28',
    title: 'Expediente 28',
    description: 'Descripción del expediente 28',
    fechaLimite: '2025-10-23',
    relevancia: 1,
    especialidad: 'Med. Legal',
    estado: 'Reclamar',
    observaciones: ['Caso priorizado'],
  },
  {
    id: '29',
    title: 'Expediente 29',
    description: 'Descripción del expediente 29',
    fechaLimite: '2025-10-24',
    relevancia: 5,
    especialidad: 'Neurología',
    estado: 'Letrados',
    observaciones: ['Pendiente revisión','Falta documento adjunto'],
  },
  {
    id: '30',
    title: 'Expediente 30',
    description: 'Descripción del expediente 30',
    fechaLimite: '2025-10-25',
    relevancia: 4,
    especialidad: 'Oftalmologia',
    estado: 'Documentacion',
    observaciones: ['Asignado a nuevo responsable'],
  },
  {
    id: '31',
    title: 'Expediente 31',
    description: 'Descripción del expediente 31',
    fechaLimite: '2025-10-26',
    relevancia: 2,
    especialidad: 'Rehabilitacion',
    estado: 'Asignar',
    observaciones: ['Se solicitó información adicional'],
  },
  {
    id: '32',
    title: 'Expediente 32',
    description: 'Descripción del expediente 32',
    fechaLimite: '2025-10-27',
    relevancia: 3,
    especialidad: 'Neurología',
    estado: 'Corregir',
    observaciones: ['Pendiente revisión'],
  },
  {
    id: '33',
    title: 'Expediente 33',
    description: 'Descripción del expediente 33',
    fechaLimite: '2025-10-28',
    relevancia: 5,
    especialidad: 'Neurología',
    estado: 'Asignar',
    observaciones: ['Caso priorizado','Falta documento adjunto'],
  },
  {
    id: '34',
    title: 'Expediente 34',
    description: 'Descripción del expediente 34',
    fechaLimite: '2025-10-29',
    relevancia: 1,
    especialidad: 'Maxilo Facial',
    estado: 'Otros',
    observaciones: ['En espera de respuesta'],
  },
  {
    id: '35',
    title: 'Expediente 35',
    description: 'Descripción del expediente 35',
    fechaLimite: '2025-10-30',
    relevancia: 2,
    especialidad: 'Odontologia',
    estado: 'Q',
    observaciones: ['Asignado a nuevo responsable'],
  },
  {
    id: '36',
    title: 'Expediente 36',
    description: 'Descripción del expediente 36',
    fechaLimite: '2025-10-31',
    relevancia: 4,
    especialidad: 'Psiquiatria',
    estado: 'Asignar',
    observaciones: ['Requiere actualización de datos'],
  },
  {
    id: '37',
    title: 'Expediente 37',
    description: 'Descripción del expediente 37',
    fechaLimite: '2025-10-03',
    relevancia: 5,
    especialidad: 'Trauma',
    estado: 'Letrados',
    observaciones: ['Pendiente revisión'],
  },
  {
    id: '38',
    title: 'Expediente 38',
    description: 'Descripción del expediente 38',
    fechaLimite: '2025-10-05',
    relevancia: 2,
    especialidad: 'ORL',
    estado: 'Corregir',
    observaciones: ['Falta documento adjunto', 'Se solicitó información adicional'],
  },
  {
    id: '39',
    title: 'Expediente 39',
    description: 'Descripción del expediente 39',
    fechaLimite: '2025-10-10',
    relevancia: 3,
    especialidad: 'Med. Legal',
    estado: 'Asignar',
    observaciones: ['Caso priorizado'],
  },
  {
    id: '40',
    title: 'Expediente 40',
    description: 'Descripción del expediente 40',
    fechaLimite: '2025-10-12',
    relevancia: 4,
    especialidad: 'Neurología',
    estado: 'Documentacion',
    observaciones: ['En espera de respuesta'],
  },
  {
    id: '41',
    title: 'Expediente 41',
    description: 'Descripción del expediente 41',
    fechaLimite: '2025-10-14',
    relevancia: 1,
    especialidad: 'Oftalmologia',
    estado: 'Q',
    observaciones: ['Asignado a nuevo responsable'],
  },
  {
    id: '42',
    title: 'Expediente 42',
    description: 'Descripción del expediente 42',
    fechaLimite: '2025-10-16',
    relevancia: 5,
    especialidad: 'Med. Trabajo',
    estado: 'Asignar',
    observaciones: ['Pendiente revisión','Falta documento adjunto'],
  },
  {
    id: '43',
    title: 'Expediente 43',
    description: 'Descripción del expediente 43',
    fechaLimite: '2025-10-18',
    relevancia: 2,
    especialidad: 'Maxilo Facial',
    estado: 'Letrados',
    observaciones: ['Se solicitó información adicional'],
  },
  {
    id: '44',
    title: 'Expediente 44',
    description: 'Descripción del expediente 44',
    fechaLimite: '2025-10-20',
    relevancia: 3,
    especialidad: 'Neurología',
    estado: 'Reclamar',
    observaciones: ['Caso priorizado'],
  },
  {
    id: '45',
    title: 'Expediente 45',
    description: 'Descripción del expediente 45',
    fechaLimite: '2025-10-22',
    relevancia: 4,
    especialidad: 'Trauma',
    estado: 'Asignar',
    observaciones: ['En espera de respuesta', 'Falta documento adjunto'],
  },
  {
    id: '46',
    title: 'Expediente 46',
    description: 'Descripción del expediente 46',
    fechaLimite: '2025-10-24',
    relevancia: 1,
    especialidad: 'Ginecologia',
    estado: 'Otros',
    observaciones: ['Pendiente revisión'],
  },
  {
    id: '47',
    title: 'Expediente 47',
    description: 'Descripción del expediente 47',
    fechaLimite: '2025-10-26',
    relevancia: 2,
    especialidad: 'Psiquiatria',
    estado: 'Asignar',
    observaciones: ['Asignado a nuevo responsable'],
  },
  {
    id: '48',
    title: 'Expediente 48',
    description: 'Descripción del expediente 48',
    fechaLimite: '2025-10-28',
    relevancia: 5,
    especialidad: 'Med. Legal',
    estado: 'Reclamar',
    observaciones: ['Se solicitó información adicional', 'Caso priorizado'],
  },
  {
    id: '49',
    title: 'Expediente 49',
    description: 'Descripción del expediente 49',
    fechaLimite: '2025-10-30',
    relevancia: 3,
    especialidad: 'Neurología',
    estado: 'Q',
    observaciones: ['Falta documento adjunto'],
  },
  {
    id: '50',
    title: 'Expediente 50',
    description: 'Descripción del expediente 50',
    fechaLimite: '2025-10-31',
    relevancia: 4,
    especialidad: 'Odontologia',
    estado: 'Asignar',
    observaciones: ['Pendiente revisión'],
  },
];

